track learner groups list sort criteria in url.
ilios/frontend pull request #6642
Opened 2022-04-25 22:44 UTC by stopfstedt

fixes https://github.com/ilios/frontend/issues/6641

2022-04-27 23:07 UTC, dartajax approved these changes
I like it.

2022-04-28 03:49 UTC, jrjohnson requested changes

2022-04-28 03:49 UTC, jrjohnson commented on tests/integration/components/instructor-groups/list-test.js
> +      @setSortBy={{this.sortBy}}
```suggestion
      @setSortBy={{(noop)}}
```

I don't think `this.sortBy` exists.

2022-04-28 15:45 UTC, stopfstedt commented on tests/integration/components/instructor-groups/list-test.js
> +      @setSortBy={{this.sortBy}}
fixed :heavy_check_mark:

2022-04-28 16:32 UTC, merged