GraphQL Subject Reports
ilios/frontend pull request #7015
Opened 2023-01-18 07:03 UTC by jrjohnson

Taking advantage of our GraphQL endpoints for our existing subject reports speeds up query and rendering for these reports.

Because we no longer need so much boilerplate for loading the report results I've been able to split each report into its own component and handler rendering in templates which should make it much easier to augment reports with more data or formatting in the future.

WIP:
- [ ] needs to be tested with lots of real reports, but will require an API bump

2023-01-24 20:25 UTC, stopfstedt approved these changes

2023-01-24 23:08 UTC, dartajax approved these changes
looks good to me

2023-01-24 23:16 UTC, dartajax commented
This report did not return data on the PR version but it did return data on demo. The report is session types based on instructor selected. Here it is from the PR version ...

<img width="714" alt="image" src="https://user-images.githubusercontent.com/7493331/214442228-8699e53e-9a06-4e7f-9277-ccc15951532b.png">

Here it is from demo ...

![image](https://user-images.githubusercontent.com/7493331/214442327-3dc98500-b0c7-4c3a-80c6-337c59e74924.png)

2023-01-24 23:18 UTC, dartajax commented
It appears to be fine when querying for session types based on term (well I think it's term anyway).

2023-01-24 23:22 UTC, dartajax requested changes
see my recent comments - Session Types by Instructor didn't return any data using this Netlify PR deploy build or whatever - but records were returned using demo

2023-01-25 00:22 UTC, dartajax approved these changes

2023-01-25 19:47 UTC, dartajax commented
This one was from the All Terms in All Schools report. Data is slightly different between demo and this PR also - not sure which is more accurate or appropriate.

![image](https://user-images.githubusercontent.com/7493331/214672717-efe27adc-f23f-4f8c-97ab-c5b0cc196323.png)

2023-02-02 20:29 UTC, dartajax commented
All Session Types >> All Schools >> MeSH not returning in GraphQL but ok on Netlify front-end environment

![image](https://user-images.githubusercontent.com/7493331/216442524-f58d8291-4232-4c18-9a74-15ecc706bed0.png)

![image](https://user-images.githubusercontent.com/7493331/216442615-41766de6-4118-4a66-beec-a55b9d107a41.png)

2023-02-08 08:04 UTC, jrjohnson commented
@dartajax - ready for a last round of testing I think and can be merged if it meets with your approval.

2023-02-10 17:46 UTC, dartajax commented
In This PR, no results found for the following ...

![image](https://user-images.githubusercontent.com/7493331/218160224-8b68bdf7-ca9b-4475-a780-8d8c785f786e.png)

On demo and Netlify, 4 results are found ...

![image](https://user-images.githubusercontent.com/7493331/218160500-d17287a4-bde2-48ca-9546-f95c4030464c.png)

2023-02-10 18:04 UTC, dartajax commented
Sort order – all LM’s by Session Type – Lecture – the first in the sort I suspect have leading blanks – which should be trimmed and then it goes to quotes, numbers, and finally regular A-Z – at least in the sort order we should ignore the leading blank spaces 
 
The screen shot below shows where it changes the sort from [blank space first or whatever is going on here to orphan these records] to [quotations] - this is if and only if there are blank spaces in the LM titles such as ` Addiction 101 Video` - I don't see it when looking it up on prod in the database.
 
![image](https://user-images.githubusercontent.com/7493331/218162462-5d90c60b-a4c0-4117-99e2-3596e61808c5.png)

2023-02-10 19:53 UTC, dartajax commented
From demo (same as netlify)

![image](https://user-images.githubusercontent.com/7493331/218184997-c47befa1-be19-4f24-8535-8fe96feb564a.png)

From the PR (same report)

![image](https://user-images.githubusercontent.com/7493331/218185112-e253dd4b-efec-4464-a245-9227ffb1e537.png)

2023-02-10 19:58 UTC, dartajax commented
Font is ever so slightly larger with the Graph QL PR than it is on demo (lower screen shot)

![image](https://user-images.githubusercontent.com/7493331/218185857-80ebded2-0a3e-4a0c-b762-532fb3a2a3dc.png)

![image](https://user-images.githubusercontent.com/7493331/218186006-303ef822-8346-46bf-88a4-fd059ac1b0c6.png)

2023-02-10 22:06 UTC, dartajax commented
This is Session Types by MeSH -- on demo ...

![image](https://user-images.githubusercontent.com/7493331/218206995-7f6275dc-b119-4c99-a45e-4bcf4063a6e4.png)

From the PR netlify ...

![image](https://user-images.githubusercontent.com/7493331/218207092-69a9e088-e816-4ecf-8a99-0db224326b5c.png)

There is a divergence in data here. I think the return of "Lecture" is correct. I can go attach that MeSH to a different session type to verify. Wow so I added this MeSH term to a session of type "Practical (Lab) Exam" and it got added to "Lecture" on the demo and netlify latest versions AND it got returned by Graph QL - maybe Graph QL is the most accurate - either way, diverging data gets me to report out on it.

2023-02-14 23:28 UTC, merged