replace await in templates for learnergroup management components.
ilios/frontend pull request #7121
Opened 2023-04-07 19:57 UTC by stopfstedt

refs https://github.com/ilios/ilios/issues/4651

2023-04-07 22:42 UTC, jrjohnson requested changes

2023-04-07 22:42 UTC, jrjohnson commented on app/components/learner-group/bulk-assignment.js
> +  @use allDescendants = new ResolveAsyncValue(() => [this.args.learnerGroup.allDescendants, []]);
`learnerGroup.allDescendants` isn't async it's a getter on the model and can be access directly as it will return an array when it's empty.

2023-04-07 22:42 UTC, jrjohnson commented on app/components/learner-group/bulk-assignment.hbs
> +              @groups={{sort-by "title" this.allDescendants}}
```suggestion
              @groups={{sort-by "title" @learnerGroup.allDescendants}}
```
await wasn't doing anything here.

2023-04-07 22:42 UTC, jrjohnson commented on app/components/learner-group/instructor-group-members-list.js
> +    return this.membersResource ? this.membersResource.slice() : [];
why the `slice`?

2023-04-07 22:42 UTC, jrjohnson commented on app/components/learner-group/instructor-manager.js
> +    return this.allInstructorsResource ? this.allInstructorsResource.slice() : [];
why slice?

2023-04-17 22:35 UTC, stopfstedt commented on app/components/learner-group/instructor-group-members-list.js
> +    return this.membersResource ? this.membersResource.slice() : [];
:heavy_check_mark:

2023-04-17 22:35 UTC, stopfstedt commented on app/components/learner-group/instructor-manager.js
> +    return this.allInstructorsResource ? this.allInstructorsResource.slice() : [];
:heavy_check_mark:

2023-04-18 05:39 UTC, jrjohnson approved these changes

2023-04-18 15:46 UTC, merged