Move ICS Feed button from Ilios Calendar to Main Navigation
ilios/frontend pull request #7811
Opened 2024-05-07 16:04 UTC by michaelchadwick

Fixes ilios/ilios#4116.

The old functionality is to click on Calendar in the main navigation, click the ICS Feed button, and then click the "Copy My ICS Link" button in the flyout to copy the URL to the user's clipboard.

![ilios-ics-pre](https://github.com/ilios/frontend/assets/2374391/509c9de5-1c8e-4cfb-9e90-6ffed1ae99f7)

The new functionality is to click the ICS Feed button to copy the URL to the user's clipboard, directly from the main navigation, always available, and without the flyout.

![ilios-ics-post](https://github.com/ilios/frontend/assets/2374391/5f530b19-34a3-4d58-8a67-c71ba352b710)

Tests for this are still being figured out, so this is a draft for now.

2024-05-07 23:07 UTC, michaelchadwick commented
I wasn't able to figure out how to test the new tooltip notification upon clicking the ICS Feed button, but I removed some testing code that was no longer relevant.

2024-05-08 14:55 UTC, jrjohnson reviewed
I think putting this here was my idea, but now that it's here I don't love it. It feels like too prominent a location for this and doesn't balance particularly well with the other buttons. Some discussion needed for sure. Maybe in the profile menu?

The tooltip copy works, but I think we have some better options. Take a look at:
1. The copy button on a virtual learning URL in an offering
2. The copy button on the API key generator at the bottom of the user profile page

I didn't look too deeply at the code as is, think we need to work out some UX first.

2024-05-08 20:26 UTC, michaelchadwick commented
The API key copy notification is nice, yes, and could be used instead. As for the placement of the icon itself, I don't have a strong feeling one way or another. It looks like the user profile menu is pretty bare and could easily incorporate more functionality. However, would users know to look there for this?

2024-05-09 22:35 UTC, michaelchadwick commented
All righty: I changed the button to have an IliosTooltip on mouse hover, and the click success triggers a flash message instead.

2024-05-15 15:50 UTC, jrjohnson requested changes
Can you have the tooltip pop out to the right instead of underneath when there is space? If this ends up being more than an hour's work never mind. I'd also like to see the button switch to a check after it is clicked along with the confirmation.

2024-06-12 22:17 UTC, michaelchadwick commented
Moved the tooltip so it displays to the right. If there's no room, then it falls back to bottom.

As for the icon itself turning into a checkmark, you mean you want the copy button to go from RSS Feed (pre-click)->Checkmark (clicked)->RSS Feed (post-click)?

2024-07-18 18:13 UTC, jrjohnson approved these changes

2024-07-18 18:13 UTC, jrjohnson commented
Code looks good, assigning to @dartajax for another visual pass and merge.

2024-07-18 19:05 UTC, dartajax commented
percy won't let me merge this one either but quick assumption - it looks like the .ics feed button is snuggling up to the Calendar button - they are related but is this visual representation intentional? I am cool with it just wondering

2024-07-18 19:10 UTC, dartajax commented
we need to be aware - other support people as well as me - that when a user clicks Calendar, the screen shifts and the top menu is not viewable meaning that they may not be able to find the .ics feed button since it has been moved to the top of the screen - just pointing this out

2024-07-18 20:37 UTC, michaelchadwick commented
> ...it looks like the .ics feed button is snuggling up to the Calendar button - they are related but is this visual representation intentional? I am cool with it just wondering

@dartajax The visual representation is intentional per https://github.com/ilios/ilios/issues/4116#issuecomment-2025798087.

2024-07-18 20:42 UTC, michaelchadwick commented
> we need to be aware...that when a user clicks Calendar, the screen shifts and the top menu is not viewable meaning that they may not be able to find the .ics feed button since it has been moved to the top of the screen

@dartajax This is a good point. I'm not sure how often people use this icon link, so not sure if it matters, though. @jrjohnson and @stopfstedt, thoughts?

2024-07-18 21:11 UTC, dartajax commented
> > we need to be aware...that when a user clicks Calendar, the screen shifts and the top menu is not viewable meaning that they may not be able to find the .ics feed button since it has been moved to the top of the screen
> 
> @dartajax This is a good point. I'm not sure how often people use this icon link, so not sure if it matters, though. @jrjohnson and @stopfstedt, thoughts?

My $.02 is that most students grab their feed from here so a lot of people use it. But we are in summer right now and new students can have a new interface and updated instructions on grabbing their feeds.

2024-07-19 18:14 UTC, jrjohnson commented
I think the scrolling display is a different issue, we don't need to consider it here. Percy has now run, just needs someone to check and make sure all the changes are valid.

2024-07-19 22:37 UTC, merged