rm home-grown set helper, use ember-set-helper instead.
ilios/frontend pull request #8087
Opened 2024-08-21 00:21 UTC by stopfstedt

refs https://github.com/ilios/ilios/issues/5663

2024-08-21 15:41 UTC, jrjohnson commented
The `ember-set-helper` implementation has a different API than our version:
Us:
`{{set this.foo 'bar'}}`
Them
`{{set this 'foo' 'bar'}}`

Our transform and `ember-simple-set` before us goes through and extracts the `.` (dot) so we can do `this.foo` instead of `this "foo"`. I'd be ok with making this change, but it's a big lift.

2024-08-21 19:04 UTC, stopfstedt commented
i'm shelving this for the moment, but plan on getting back into it next week.

2024-09-06 23:02 UTC, stopfstedt commented
regex search/replace for the win.

2024-09-09 15:54 UTC, jrjohnson requested changes
Excellent. I hate this syntax, but love getting rid of our special ❄️ transform.

2024-09-09 15:57 UTC, stopfstedt commented on packages/frontend/.lint-todo
> +remove|ember-template-lint|no-at-ember-render-modifiers|5|4|5|4|ddf86727990ead62165fe28c6dff53552a4d49b7|1722902400000|1730682000000|1754006400000|app/components/user-menu.hbs
handled. :heavy_check_mark:

2024-09-09 16:16 UTC, jrjohnson approved these changes

2024-09-09 17:17 UTC, merged