Clean up FaIcon template's class attribute
ilios/frontend pull request #8128
Opened 2024-09-10 20:40 UTC by michaelchadwick

Currently, the `<FaIcon>` has an overstuffed `class` attribute that often has conditionals that are not met. This moves all the extra optional classes to a class function and only adds them in (and the spaces between them) if they are passed in.

2024-09-10 23:38 UTC, jrjohnson reviewed
I think, but haven't confirmed, that you have to do some extra work to mark this string as safe before ember will let you use it like this. That might be old school though. But worth checking for sure and I wanted to add a note.

2024-09-11 19:22 UTC, stopfstedt approved these changes
LGTM

2024-09-11 19:26 UTC, stopfstedt commented
> I think, but haven't confirmed, that you have to do some extra work to mark this string as safe before ember will let you use it like this. That might be old school though. But worth checking for sure and I wanted to add a note.

i don't think that's necessary anymore. check out the `flip` getter as it is current implemented https://github.com/ilios/frontend/blob/master/packages/ilios-common/addon/components/fa-icon.js#L25 - no safe-string marking there either, and it works.

2024-09-12 00:39 UTC, stopfstedt requested changes
needs a whitespace as separator in the class attribute, otherwise the icon flipping won't work.

for example, this can be seen in the user admin pagination

![image](https://github.com/user-attachments/assets/371ee8d5-562f-4fa9-a3f8-497e6cfd97f8)

2024-09-12 00:39 UTC, stopfstedt commented on packages/ilios-common/addon/components/fa-icon.hbs
> +  class="awesome-icon fa-{{@icon}}{{this.extraClasses}}"
needs a space here

```suggestion
  class="awesome-icon fa-{{@icon}} {{this.extraClasses}}"
```

2024-09-12 22:58 UTC, stopfstedt approved these changes
LGTM

2024-09-12 23:35 UTC, dartajax commented
> can't merge this one or restart (re-start) the test

that's because one of the test is still running - never mind

2024-09-13 18:15 UTC, merged