Reports->Sessions objectives now use multiple columns
ilios/frontend pull request #8172
Opened 2024-10-01 22:50 UTC by michaelchadwick

Not ideal yet, but was able to figure out how to push a session's objectives into their own columns.

Next, trying to push them into their own rows...

2025-04-30 18:34 UTC, dartajax reviewed
This is interesting - I put `NEEDS TEAM DISCUSSION` on there so we could discuss the labeling of the objectives outputted - whether to simply increment them which may give a sense of prioritization  which may not be accurate. It does shorten the length of the output file and make it much wider I guess too. Let's discuss.

2025-05-06 20:10 UTC, michaelchadwick commented
@dartajax I removed the numbering of Objectives. Hopefully that's enough to get this through.

2025-05-06 20:27 UTC, dartajax approved these changes
I think I am fine with this. It just calls each one an objective with no implied number sequence or preference. Lots of blanks of course since most sessions don't have the maximum number of objectives. I am gonna approve this but request that @saschaben take a look as well for another viewpoint.

2025-05-06 20:28 UTC, dartajax commented
Leaving the `Needs Team Discussion` on this ticket for a while yet.

2025-05-13 20:24 UTC, michaelchadwick commented
NTS: Change TRUE/FALSE to YES/NO

2025-05-14 21:28 UTC, michaelchadwick commented
@dartajax I changed TRUE/FALSE to language-dependent Yes/No for the new flags. Let me know if anything else needs changing.

2025-05-14 22:46 UTC, dartajax commented
> @dartajax I changed TRUE/FALSE to language-dependent Yes/No for the new flags. Let me know if anything else needs changing.

I really hate to do this but those flags are school-dependent - `Attendance Required` for example does not apply to School of Medicine and probably should not be included in a report for SOM - only the attributes active for any given school should appear.

2025-05-14 23:08 UTC, dartajax requested changes
I really hate to do this but those flags are school-dependent - Attendance Required for example does not apply to School of Medicine and probably should not be included in a report for SOM - only the attributes active for any given school should appear.

2025-05-16 17:19 UTC, michaelchadwick commented
@dartajax I added in checks for school configurations so the columns only appear if they make sense. If an "All Schools" report comes in I decided to just ignore the attribute columns as the code to decipher that doesn't seem worth the time. If you disagree, let me know.

2025-05-16 20:11 UTC, stopfstedt commented on packages/frontend/tests/integration/components/reports/subject/session-test.gjs
> +  test('download', async function (assert) {
this is quite interesting. @jrjohnson  check it out!

2025-05-16 20:12 UTC, stopfstedt approved these changes
LGTM. especially loving the download tests - this was something we haven't been able to figure out so far. :fire:

2025-05-16 20:51 UTC, dartajax commented
> @dartajax I added in checks for school configurations so the columns only appear if they make sense. If an "All Schools" report comes in I decided to just ignore the attribute columns as the code to decipher that doesn't seem worth the time. If you disagree, let me know.

That sounds fine = no disagreement.

2025-05-16 20:57 UTC, dartajax approved these changes
Looks fine to me.

2025-05-16 22:36 UTC, merged