adds unpublished icon to SingleEvent instances
ilios/frontend pull request #8192
Opened 2024-10-18 21:32 UTC by michaelchadwick

Fixes ilios/ilios#3473

Single Events need to show if they are unpublished just like when they're viewed on the calendar, so I added the missing icon. I also made sure to put missing mouseover text, and fixed up some tests.

2024-10-18 23:52 UTC, stopfstedt requested changes
apart from the two issues mentioned in `single-event.hbs`, this looks good to me.

however, it's missing test coverage on these icons.

please add this appropriate tests.

for reference, i'd like to point you at existing page-object attributes and integration tests. please see https://github.com/ilios/frontend/blob/4718d3749813d2a3b96d063915db31febe7cd4f8/packages/test-app/tests/integration/components/weekly-calendar-event-test.js#L418-L486

2024-10-18 23:52 UTC, stopfstedt commented on packages/ilios-common/addon/components/single-event.hbs
> +        {{#if (not this.isPublished)}}
should be checking `isPublished` on `@event`, not `this`. 

```suggestion
        {{#if (not @event.isPublished)}}
```

2024-10-18 23:52 UTC, stopfstedt commented on packages/ilios-common/addon/components/single-event.hbs
> +        {{else if this.isScheduled}}
should be checking `isScheduled` on `@event`, not `this`.

```suggestion
        {{else if @event.isScheduled}}
```

2024-10-19 00:03 UTC, michaelchadwick commented
Thanks for the review, @stopfstedt! I'll get back to this soon.

2024-10-24 00:51 UTC, stopfstedt approved these changes
LGTM

2024-10-25 22:29 UTC, merged