Remove ChooseMaterialTypeComponent render modifiers
ilios/frontend pull request #8266
Opened 2024-12-12 00:25 UTC by michaelchadwick

Refs ilios/ilios#5374

2024-12-13 19:42 UTC, jrjohnson approved these changes
I like the extra cleanup this forced. Nice.

2024-12-13 19:52 UTC, stopfstedt requested changes

2024-12-13 20:00 UTC, jrjohnson commented on packages/ilios-common/addon/components/choose-material-type.js
> +    document.querySelector('.choose-material-type .menu button:first-of-type').focus();
Nice catch, I didn't see this at all!

2024-12-16 16:50 UTC, stopfstedt approved these changes
LGTM

2024-12-16 18:33 UTC, merged